FROM node:14-alpine AS builder
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
#COPY yarn.lock .
RUN yarn install --development
# Copy app files
COPY . .
#install env-cmd
RUN npm install env-cmd
# Build the app
RUN yarn build:dev

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as development
ENV NODE_ENV development
# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
