version: '3.8'

networks:
  booking_lunch_dev:

services:
  mysql_booking_lunch:
    image: mysql:5.7.39 
    container_name: mysql_booking_lunch
    restart: unless-stopped
    tty: true 
    ports:
      - "4301:3306"
    environment:
      MYSQL_DATABASE: mysql_booking_lunch
      MYSQL_USER: root_
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql/
    networks:
      - booking_lunch_dev

  # Optional GUI for mysql
  adminer_booking_lunch:
    image: adminer
    container_name: adminer_booking_lunch
    restart: unless-stopped
    ports:
      - 8095:8080
    networks:
      - booking_lunch_dev